// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onIftttCounterChange();
void onLightChange();
void onThresholdChange();

CloudCounter ifttt_counter;
int light;
int threshold;

void initProperties(){

  ArduinoCloud.addProperty(ifttt_counter, READWRITE, ON_CHANGE, onIftttCounterChange, 1);
  ArduinoCloud.addProperty(light, READWRITE, ON_CHANGE, onLightChange);
  ArduinoCloud.addProperty(threshold, READWRITE, 5 * SECONDS, onThresholdChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
